# This file can be used to build and run the gateway-lite container from the current source tree
# See the README.md for normal use where you'll use the published docker image directly.

version: "3"
services:
  gateway:
    restart: unless-stopped
    build: ./
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./domain:/app/domain:rw
      - ./letsencrypt:/etc/letsencrypt:rw
    environment:
      DEBUG: gateway-lite
    command: >
      --https-port 443
      --port 80
      --cert domain/www.example.localhost/sni/cert.pem
      --key domain/www.example.localhost/sni/key.pem
      --proxy '
        www.example.localhost:
          - ["/", "downstream:80", {"limit": "100mb"}]
      '
      --domain domain
    links:
      - downstream:downstream
  downstream:
    restart: unless-stopped
    environment:
      PORT: 80
      DEBUG: express-downstream,express-downstream:debug
      NAME: "Downstream"
      SCRIPT_NAME: ""
    image: thejimmyg/express-downstream:0.1.2
    expose:
      - 80
